<Project>
  <PropertyGroup>
    <EnableSourceLink>false</EnableSourceLink>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
    <DeterministicSourcePaths>false</DeterministicSourcePaths>
    <SourceControlInformationFeatureSupported>false</SourceControlInformationFeatureSupported>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
