spring.datasource.url=jdbc:h2:file:./booksdb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.mode=always

server.port=8080
