spring.application.name=books-api
spring.datasource.url=jdbc:sqlite:books.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=1
spring.jackson.default-property-inclusion=non_null
server.port=8080
